// Ports the approved Glim mascot (docs/brand/glim-mascot.html) into the app:
// writes src/mascot/lantern.css and src/mascot/lantern-svg.ts from it.
//
//   node scripts/port-lantern.mjs           writes both files
//   node scripts/port-lantern.mjs --check   fails if either is out of date
//
// The design file is the source of truth; these files are generated from it
// and never edited by hand. The port changes nothing about how the lantern
// looks. It only does what embedding it in a bigger page needs:
//
// - CSS: only the lantern's rules (from `.lantern{display:block…}` to the
//   reduced-motion rule) are kept; the demo page's body, buttons and controls
//   are dropped. Selectors that the design file left unscoped (`.s-idle …`,
//   `.compact …`, `.aura`, `.tw`, `.mote`, …) are scoped to `.lantern`, so they
//   can't reach the rest of the app; each rule keeps its relative order, and
//   every state/compact rule rises by the same specificity, so the cascade
//   inside the lantern is unchanged. Keyframes get a `lantern-` prefix (unless
//   the design already gave them one) because the app already has a global
//   `@keyframes pulse`; references through `animation` and `animation-name`
//   follow.
// - SVG: the markup inside <svg> is kept verbatim except that every id
//   (`lg-glow`, `lg-paper`, …) and every `url(#…)` pointing at one gets a
//   `{ID}` suffix, which src/mascot/lantern.ts replaces per instance so two
//   lanterns on one page never share a gradient, filter or clip path.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, "../../docs/brand/glim-mascot.html");
const CSS_OUT = resolve(here, "../src/mascot/lantern.css");
const SVG_OUT = resolve(here, "../src/mascot/lantern-svg.ts");

const HEADER = "Generated by scripts/port-lantern.mjs from docs/brand/glim-mascot.html. Do not edit: run `node scripts/port-lantern.mjs`.";

/** Splits CSS text into top-level blocks: `selector{…}` and `@rule{…{…}…}`. */
function blocks(css) {
  const out = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}") {
      depth--;
      if (depth === 0) {
        out.push(css.slice(start, i + 1).trim());
        start = i + 1;
      }
    }
  }
  if (css.slice(start).trim()) throw new Error(`unparsed CSS: ${css.slice(start).trim()}`);
  return out;
}

function scopeSelector(sel) {
  sel = sel.trim();
  if (sel.startsWith(".lantern")) return sel;
  // A state or size class sits on the <svg> itself.
  if (/^\.(s-[a-z]+|compact)\b/.test(sel)) return `.lantern${sel}`;
  return `.lantern ${sel}`;
}

export function portCss(html) {
  const style = html.match(/<style>([\s\S]*?)<\/style>/)?.[1];
  if (!style) throw new Error("no <style> in the design file");
  const first = style.indexOf(".lantern{display:block");
  const media = style.indexOf("@media (prefers-reduced-motion");
  if (first < 0 || media < 0) throw new Error("the design file's lantern CSS has moved");
  const end = style.indexOf("\n", media);
  const css = style.slice(first, end < 0 ? undefined : end);

  // Keyframes the design already prefixed (`lantern-hop`) keep their name.
  const names = [...css.matchAll(/@keyframes ([a-z-]+)/g)].map((m) => m[1]);
  const prefixed = (name) => (name.startsWith("lantern-") ? name : `lantern-${name}`);
  // Both the shorthand and `animation-name:` (`.compact.s-listen .eyes`) name them.
  const rename = (text) =>
    text.replace(/(animation(?:-name)?:\s*)([a-z-]+)/g, (m, pre, name) => (names.includes(name) ? `${pre}${prefixed(name)}` : m));

  const out = [];
  for (const block of blocks(css)) {
    if (block.startsWith("@keyframes ")) {
      out.push(block.replace(/^@keyframes ([a-z-]+)/, (m, name) => `@keyframes ${prefixed(name)}`));
    } else if (block.startsWith("@media")) {
      out.push(rename(block)); // `.lantern *{animation:none !important}`: already scoped
    } else {
      const brace = block.indexOf("{");
      const selectors = block.slice(0, brace).split(",").map(scopeSelector).join(",");
      out.push(selectors + rename(block.slice(brace)));
    }
  }
  return `/* ${HEADER} */\n${out.join("\n")}\n`;
}

export function portSvg(html) {
  const svg = html.match(/<svg ([^>]*)>([\s\S]*?)<\/svg>/);
  if (!svg) throw new Error("no <svg> in the design file");
  const viewBox = svg[1].match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error("the design's <svg> has no viewBox");
  const ids = [...svg[2].matchAll(/ id="([^"]+)"/g)].map((m) => m[1]);
  let body = svg[2].trim();
  for (const id of ids) {
    body = body.replaceAll(`id="${id}"`, `id="${id}-{ID}"`).replaceAll(`url(#${id})`, `url(#${id}-{ID})`);
  }
  return [
    `// ${HEADER}`,
    "",
    "/** The design's viewBox. */",
    `export const LANTERN_VIEWBOX = ${JSON.stringify(viewBox)};`,
    "",
    "/** Every id the markup defines; each carries the `{ID}` placeholder. */",
    `export const LANTERN_IDS = ${JSON.stringify(ids)} as const;`,
    "",
    "/** The markup inside the design's <svg>, verbatim apart from the id suffixes. */",
    `export const LANTERN_MARKUP = ${JSON.stringify(body)};`,
    "",
  ].join("\n");
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const html = readFileSync(SOURCE, "utf8");
  const files = [
    [CSS_OUT, portCss(html)],
    [SVG_OUT, portSvg(html)],
  ];
  if (process.argv.includes("--check")) {
    const stale = files.filter(([path, text]) => {
      try {
        return readFileSync(path, "utf8").replace(/\r\n/g, "\n") !== text;
      } catch {
        return true;
      }
    });
    if (stale.length) {
      console.error(`out of date: ${stale.map(([p]) => p).join(", ")} — run \`node scripts/port-lantern.mjs\`.`);
      process.exit(1);
    }
    console.log("src/mascot is up to date with docs/brand/glim-mascot.html.");
  } else {
    for (const [path, text] of files) writeFileSync(path, text);
    console.log(`Wrote ${CSS_OUT} and ${SVG_OUT}`);
  }
}
